### ISSUE TITLE
Hello, what injector do you use? I can't inject witch it

### ISSUE THREAD

**Issue by YMY1666527646** [guttir14/CheatIt#2]
Try to take the signature from the UnrealDumper-4.25 project

The signature is updated, but the injection still fails

Face injector witch it , game crash

**Comment by reddude256** [comment]
Same

**Comment by YMY1666527646** [comment]
> Same

I always use extreme injector
When I use another injector, it indicates that the injection is successful, but (cheating doesn't work)

**Comment by YMY1666527646** [comment]
witch it
Switch it is a game without any protection. I think it can be injected by using any injector

**Comment by reddude256** [comment]
I'm playing Polygon I got another cheat to work though so i'm just using that with Face Injector

**Comment by YMY1666527646** [comment]
> I'm playing Polygon I got another cheat to work though so i'm just using that with Face Injector

🤣

**Comment by reddude256** [comment]
Yes
